string target_prompt
bool enable_avoidance
geometry_msgs/PoseStamped approximate_target_pose
---
bool success
string reason
geometry_msgs/PoseStamped final_grasp_pose
float32 lift_height
uint8 attempts
---
string stage
float32 target_visible_score
float32 grasp_score
float32 tcp_pos_err
float32 tcp_ori_err
float32 sdf_min_dist
bool cbf_active
bool tracking_valid
bool replan_running
string reason
